'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System



'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option or rebuild the Visual Studio project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0"), _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()> _
Public Class AssetPaths

    Private Shared resourceMan As Global.System.Resources.ResourceManager

    Private Shared resourceCulture As Global.System.Globalization.CultureInfo

    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")> _
    Public Sub New()
        MyBase.New()
    End Sub

    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.AssetPaths", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property

    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Public Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set(value As Global.System.Globalization.CultureInfo)
            resourceCulture = value
        End Set
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/Images/apple-touch-icon-114x114-f1d7ccdc7b86d923386b373a9ba5e3db.png.
    '''</summary>
    Public Shared ReadOnly Property apple_touch_icon_114x114_png() As String
        Get
            Return ResourceManager.GetString("apple_touch_icon_114x114_png", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/Images/apple-touch-icon-144x144-4e306e01c31e237722b82b7aa7130082.png.
    '''</summary>
    Public Shared ReadOnly Property apple_touch_icon_144x144_png() As String
        Get
            Return ResourceManager.GetString("apple_touch_icon_144x144_png", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/Images/apple-touch-icon-57x57-37527434942ed8407b091aae5feff3f3.png.
    '''</summary>
    Public Shared ReadOnly Property apple_touch_icon_57x57_png() As String
        Get
            Return ResourceManager.GetString("apple_touch_icon_57x57_png", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/Images/apple-touch-icon-72x72-2ddbe540853e3ba0d30fbad2a95eab3c.png.
    '''</summary>
    Public Shared ReadOnly Property apple_touch_icon_72x72_png() As String
        Get
            Return ResourceManager.GetString("apple_touch_icon_72x72_png", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to .
    '''</summary>
    Public Shared ReadOnly Property AssetURLWithTrailingSlashAndFolder() As String
        Get
            Return ResourceManager.GetString("AssetURLWithTrailingSlashAndFolder", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/Scripts/core.js?19.
    '''</summary>
    Public Shared ReadOnly Property core_js() As String
        Get
            Return ResourceManager.GetString("core_js", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/Images/favicon-447e4ac1ab790342660eacfe3dcce264.ico.
    '''</summary>
    Public Shared ReadOnly Property favicon_ico() As String
        Get
            Return ResourceManager.GetString("favicon_ico", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/gds/fonts-607c54f71c7c1f98257595cedaa13a34.css.
    '''</summary>
    Public Shared ReadOnly Property fonts_css() As String
        Get
            Return ResourceManager.GetString("fonts_css", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/gds/fonts-ie8-ec274e547d95d22db00164cc291c8611.css.
    '''</summary>
    Public Shared ReadOnly Property fonts_ie8_css() As String
        Get
            Return ResourceManager.GetString("fonts_ie8_css", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/Images/gov.uk_logotype-2x-24145374d271079f08d96c618cc8d4a5.png.
    '''</summary>
    Public Shared ReadOnly Property govuk_logotype_2x_png() As String
        Get
            Return ResourceManager.GetString("govuk_logotype_2x_png", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/Images/gov.uk_logotype_crown.png.
    '''</summary>
    Public Shared ReadOnly Property govuk_logotype_crown_png() As String
        Get
            Return ResourceManager.GetString("govuk_logotype_crown_png", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/Styles/govuk-template.css?19.
    '''</summary>
    Public Shared ReadOnly Property govuk_template_css() As String
        Get
            Return ResourceManager.GetString("govuk_template_css", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/Styles/govuk-template-ie6.css?19.
    '''</summary>
    Public Shared ReadOnly Property govuk_template_ie6_css() As String
        Get
            Return ResourceManager.GetString("govuk_template_ie6_css", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/Styles/govuk-template-ie7.css?19.
    '''</summary>
    Public Shared ReadOnly Property govuk_template_ie7_css() As String
        Get
            Return ResourceManager.GetString("govuk_template_ie7_css", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/Styles/govuk-template-ie8.css?19.
    '''</summary>
    Public Shared ReadOnly Property govuk_template_ie8_css() As String
        Get
            Return ResourceManager.GetString("govuk_template_ie8_css", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/Scripts/govuk-template.js?19.
    '''</summary>
    Public Shared ReadOnly Property govuk_template_js() As String
        Get
            Return ResourceManager.GetString("govuk_template_js", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/Styles/govuk-template-print.css?19.
    '''</summary>
    Public Shared ReadOnly Property govuk_template_print_css() As String
        Get
            Return ResourceManager.GetString("govuk_template_print_css", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/Styles/application-ie6-d77048f3c3c8d29dd60fcdadd1fc57e2.css.
    '''</summary>
    Public Shared ReadOnly Property ie6_css() As String
        Get
            Return ResourceManager.GetString("ie6_css", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/Styles/application-ie7-d4679c8e213c0a8a0ab0a4ddf46487b9.css.
    '''</summary>
    Public Shared ReadOnly Property ie7_css() As String
        Get
            Return ResourceManager.GetString("ie7_css", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/Styles/application-ie8-7685de5b79d3e4394e3a97136743392d.css.
    '''</summary>
    Public Shared ReadOnly Property ie8_css() As String
        Get
            Return ResourceManager.GetString("ie8_css", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/Styles/application-ac5c76582c33fd730fdc2704dc401728.css.
    '''</summary>
    Public Shared ReadOnly Property ie_css() As String
        Get
            Return ResourceManager.GetString("ie_css", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/Scripts/ie-fc5bd25c5f46587b9bff917417ab2b7f.js.
    '''</summary>
    Public Shared ReadOnly Property ie_js() As String
        Get
            Return ResourceManager.GetString("ie_js", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/gds/jquery-1.7.2-2ce4706f8f7193defaa9e7df2b641e9a.js.
    '''</summary>
    Public Shared ReadOnly Property jquery_js() As String
        Get
            Return ResourceManager.GetString("jquery_js", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/Images/loading.gif.
    '''</summary>
    Public Shared ReadOnly Property Loading() As String
        Get
            Return ResourceManager.GetString("Loading", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/Images/maestro-curved-32px.png.
    '''</summary>
    Public Shared ReadOnly Property Maestro() As String
        Get
            Return ResourceManager.GetString("Maestro", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/Images/mastercard-curved-32px.png.
    '''</summary>
    Public Shared ReadOnly Property MasterCard() As String
        Get
            Return ResourceManager.GetString("MasterCard", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/Images/opengraph-image-4e469785ca4cc8f8dd18d0627bc43d19.png.
    '''</summary>
    Public Shared ReadOnly Property opengraph_image_png() As String
        Get
            Return ResourceManager.GetString("opengraph_image_png", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/Images/open-government-licence_2x-d273d7eca3045d3b710a863d9bfc0b33.png.
    '''</summary>
    Public Shared ReadOnly Property open_government_licence_2x_png() As String
        Get
            Return ResourceManager.GetString("open_government_licence_2x_png", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/Styles/print-546864271280c5a1b3d7e8a0bbe71896.css.
    '''</summary>
    Public Shared ReadOnly Property print_css() As String
        Get
            Return ResourceManager.GetString("print_css", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/Images/CreditCard_Security_Code_Image.png.
    '''</summary>
    Public Shared ReadOnly Property Security() As String
        Get
            Return ResourceManager.GetString("Security", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/Scripts/typeahead.min.js.
    '''</summary>
    Public Shared ReadOnly Property TypeAhead() As String
        Get
            Return ResourceManager.GetString("TypeAhead", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/Images/V11_122x145.png.
    '''</summary>
    Public Shared ReadOnly Property V11() As String
        Get
            Return ResourceManager.GetString("V11", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/Images/V5C_122x145.png.
    '''</summary>
    Public Shared ReadOnly Property V5C() As String
        Get
            Return ResourceManager.GetString("V5C", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/Images/V5C2.png.
    '''</summary>
    Public Shared ReadOnly Property V5C2() As String
        Get
            Return ResourceManager.GetString("V5C2", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/Images/visa-curved-32px.png.
    '''</summary>
    Public Shared ReadOnly Property Visa() As String
        Get
            Return ResourceManager.GetString("Visa", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/Images/visa-electron-curved-32px.png.
    '''</summary>
    Public Shared ReadOnly Property VisaElectron() As String
        Get
            Return ResourceManager.GetString("VisaElectron", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Assets/gds/webfont-debug-96870cf9f159ed811fd43c39bdf4656b.js.
    '''</summary>
    Public Shared ReadOnly Property webfont_debug_js() As String
        Get
            Return ResourceManager.GetString("webfont_debug_js", resourceCulture)
        End Get
    End Property
End Class

