'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class AssetPaths
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.AssetPaths", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assets/Images/apple-touch-icon-114x114-f1d7ccdc7b86d923386b373a9ba5e3db.png.
        '''</summary>
        Friend Shared ReadOnly Property apple_touch_icon_114x114_png() As String
            Get
                Return ResourceManager.GetString("apple_touch_icon_114x114_png", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assets/Images/apple-touch-icon-144x144-4e306e01c31e237722b82b7aa7130082.png.
        '''</summary>
        Friend Shared ReadOnly Property apple_touch_icon_144x144_png() As String
            Get
                Return ResourceManager.GetString("apple_touch_icon_144x144_png", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assets/Images/apple-touch-icon-57x57-37527434942ed8407b091aae5feff3f3.png.
        '''</summary>
        Friend Shared ReadOnly Property apple_touch_icon_57x57_png() As String
            Get
                Return ResourceManager.GetString("apple_touch_icon_57x57_png", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assets/Images/apple-touch-icon-72x72-2ddbe540853e3ba0d30fbad2a95eab3c.png.
        '''</summary>
        Friend Shared ReadOnly Property apple_touch_icon_72x72_png() As String
            Get
                Return ResourceManager.GetString("apple_touch_icon_72x72_png", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assets/Scripts/core.js?10.
        '''</summary>
        Friend Shared ReadOnly Property core_js() As String
            Get
                Return ResourceManager.GetString("core_js", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assets/Images/favicon-447e4ac1ab790342660eacfe3dcce264.ico.
        '''</summary>
        Friend Shared ReadOnly Property favicon_ico() As String
            Get
                Return ResourceManager.GetString("favicon_ico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assets/Styles/fonts.css.
        '''</summary>
        Friend Shared ReadOnly Property fonts_css() As String
            Get
                Return ResourceManager.GetString("fonts_css", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assets/Styles/fonts-ie8.css.
        '''</summary>
        Friend Shared ReadOnly Property fonts_ie8_css() As String
            Get
                Return ResourceManager.GetString("fonts_ie8_css", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assets/Images/gov.uk_logotype-2x-24145374d271079f08d96c618cc8d4a5.png.
        '''</summary>
        Friend Shared ReadOnly Property govuk_logotype_2x_png() As String
            Get
                Return ResourceManager.GetString("govuk_logotype_2x_png", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assets/Images/gov.uk_logotype_crown.png.
        '''</summary>
        Friend Shared ReadOnly Property govuk_logotype_crown_png() As String
            Get
                Return ResourceManager.GetString("govuk_logotype_crown_png", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assets/Styles/govuk-template.css?10.
        '''</summary>
        Friend Shared ReadOnly Property govuk_template_css() As String
            Get
                Return ResourceManager.GetString("govuk_template_css", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assets/Styles/govuk-template-ie6.css?10.
        '''</summary>
        Friend Shared ReadOnly Property govuk_template_ie6_css() As String
            Get
                Return ResourceManager.GetString("govuk_template_ie6_css", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assets/Styles/govuk-template-ie7.css?10.
        '''</summary>
        Friend Shared ReadOnly Property govuk_template_ie7_css() As String
            Get
                Return ResourceManager.GetString("govuk_template_ie7_css", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assets/Styles/govuk-template-ie8.css?10.
        '''</summary>
        Friend Shared ReadOnly Property govuk_template_ie8_css() As String
            Get
                Return ResourceManager.GetString("govuk_template_ie8_css", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assets/Scripts/govuk-template.js?10.
        '''</summary>
        Friend Shared ReadOnly Property govuk_template_js() As String
            Get
                Return ResourceManager.GetString("govuk_template_js", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assets/Styles/govuk-template-print.css?10.
        '''</summary>
        Friend Shared ReadOnly Property govuk_template_print_css() As String
            Get
                Return ResourceManager.GetString("govuk_template_print_css", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assets/Styles/application-ie6-d77048f3c3c8d29dd60fcdadd1fc57e2.css.
        '''</summary>
        Friend Shared ReadOnly Property ie6_css() As String
            Get
                Return ResourceManager.GetString("ie6_css", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assets/Styles/application-ie7-d4679c8e213c0a8a0ab0a4ddf46487b9.css.
        '''</summary>
        Friend Shared ReadOnly Property ie7_css() As String
            Get
                Return ResourceManager.GetString("ie7_css", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assets/Styles/application-ie8-7685de5b79d3e4394e3a97136743392d.css.
        '''</summary>
        Friend Shared ReadOnly Property ie8_css() As String
            Get
                Return ResourceManager.GetString("ie8_css", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assets/Styles/application-ac5c76582c33fd730fdc2704dc401728.css.
        '''</summary>
        Friend Shared ReadOnly Property ie_css() As String
            Get
                Return ResourceManager.GetString("ie_css", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assets/Scripts/ie-fc5bd25c5f46587b9bff917417ab2b7f.js.
        '''</summary>
        Friend Shared ReadOnly Property ie_js() As String
            Get
                Return ResourceManager.GetString("ie_js", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assets/Scripts/jquery-1.7.2-2ce4706f8f7193defaa9e7df2b641e9a.js.
        '''</summary>
        Friend Shared ReadOnly Property jquery_js() As String
            Get
                Return ResourceManager.GetString("jquery_js", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assets/Images/opengraph-image-4e469785ca4cc8f8dd18d0627bc43d19.png.
        '''</summary>
        Friend Shared ReadOnly Property opengraph_image_png() As String
            Get
                Return ResourceManager.GetString("opengraph_image_png", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assets/Images/open-government-licence_2x-d273d7eca3045d3b710a863d9bfc0b33.png.
        '''</summary>
        Friend Shared ReadOnly Property open_government_licence_2x_png() As String
            Get
                Return ResourceManager.GetString("open_government_licence_2x_png", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assets/Styles/print-546864271280c5a1b3d7e8a0bbe71896.css.
        '''</summary>
        Friend Shared ReadOnly Property print_css() As String
            Get
                Return ResourceManager.GetString("print_css", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assets/Scripts/webfont-debug-96870cf9f159ed811fd43c39bdf4656b.js.
        '''</summary>
        Friend Shared ReadOnly Property webfont_debug_js() As String
            Get
                Return ResourceManager.GetString("webfont_debug_js", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
