'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class EVLText
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.EVLText", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alt VED commencement date.
        '''</summary>
        Friend Shared ReadOnly Property AltVedCommencementDate() As String
            Get
                Return ResourceManager.GetString("AltVedCommencementDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your application reference.
        '''</summary>
        Friend Shared ReadOnly Property ApplicationReferenceText() As String
            Get
                Return ResourceManager.GetString("ApplicationReferenceText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Back to payment.
        '''</summary>
        Friend Shared ReadOnly Property BackToPaymentText() As String
            Get
                Return ResourceManager.GetString("BackToPaymentText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Go back to start page.
        '''</summary>
        Friend Shared ReadOnly Property BackToStartText() As String
            Get
                Return ResourceManager.GetString("BackToStartText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Band rate.
        '''</summary>
        Friend Shared ReadOnly Property BandRate() As String
            Get
                Return ResourceManager.GetString("BandRate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel application.
        '''</summary>
        Friend Shared ReadOnly Property Cancel() As String
            Get
                Return ResourceManager.GetString("Cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend Shared ReadOnly Property CancelText() As String
            Get
                Return ResourceManager.GetString("CancelText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Once payment is taken this is a non-reversible transaction..
        '''</summary>
        Friend Shared ReadOnly Property CardDeclarationText() As String
            Get
                Return ResourceManager.GetString("CardDeclarationText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Card expiry date.
        '''</summary>
        Friend Shared ReadOnly Property CardExpiryDate() As String
            Get
                Return ResourceManager.GetString("CardExpiryDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter valid expiry date.
        '''</summary>
        Friend Shared ReadOnly Property CardExpiryDateInvalid() As String
            Get
                Return ResourceManager.GetString("CardExpiryDateInvalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter month of expiry&lt;br /&gt;.
        '''</summary>
        Friend Shared ReadOnly Property CardExpiryMonthMissing() As String
            Get
                Return ResourceManager.GetString("CardExpiryMonthMissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter year of expiry&lt;br /&gt;.
        '''</summary>
        Friend Shared ReadOnly Property CardExpiryYearMissing() As String
            Get
                Return ResourceManager.GetString("CardExpiryYearMissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Valid from date.
        '''</summary>
        Friend Shared ReadOnly Property CardIssueDate() As String
            Get
                Return ResourceManager.GetString("CardIssueDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date cannot be in the future.
        '''</summary>
        Friend Shared ReadOnly Property CardIssueDateInvalid() As String
            Get
                Return ResourceManager.GetString("CardIssueDateInvalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter date of expiry&lt;br /&gt;.
        '''</summary>
        Friend Shared ReadOnly Property CardIssueMonthMissing() As String
            Get
                Return ResourceManager.GetString("CardIssueMonthMissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Card issue number.
        '''</summary>
        Friend Shared ReadOnly Property CardIssueNumber() As String
            Get
                Return ResourceManager.GetString("CardIssueNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The issue number is invalid.
        '''</summary>
        Friend Shared ReadOnly Property CardIssueNumberInvalid() As String
            Get
                Return ResourceManager.GetString("CardIssueNumberInvalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Card issue number must be provided.
        '''</summary>
        Friend Shared ReadOnly Property CardIssueNumberMissing() As String
            Get
                Return ResourceManager.GetString("CardIssueNumberMissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter date of expiry.
        '''</summary>
        Friend Shared ReadOnly Property CardIssueYearMissing() As String
            Get
                Return ResourceManager.GetString("CardIssueYearMissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Card number.
        '''</summary>
        Friend Shared ReadOnly Property CardNumber() As String
            Get
                Return ResourceManager.GetString("CardNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Card number is invalid. The card number should be between 16 and 19 digits..
        '''</summary>
        Friend Shared ReadOnly Property CardNumberInvalid() As String
            Get
                Return ResourceManager.GetString("CardNumberInvalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter full card number.
        '''</summary>
        Friend Shared ReadOnly Property CardNumberMissing() As String
            Get
                Return ResourceManager.GetString("CardNumberMissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Last 3 digits of card security code.
        '''</summary>
        Friend Shared ReadOnly Property CardSecurityCode() As String
            Get
                Return ResourceManager.GetString("CardSecurityCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The card security code is invalid&lt;br /&gt;.
        '''</summary>
        Friend Shared ReadOnly Property CardSecurityCodeInvalid() As String
            Get
                Return ResourceManager.GetString("CardSecurityCodeInvalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter card security code.
        '''</summary>
        Friend Shared ReadOnly Property CardSecurityCodeMissing() As String
            Get
                Return ResourceManager.GetString("CardSecurityCodeMissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The last three digits on the signature strip.
        '''</summary>
        Friend Shared ReadOnly Property CardSecurityCodeText() As String
            Get
                Return ResourceManager.GetString("CardSecurityCodeText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Card surcharge paid.
        '''</summary>
        Friend Shared ReadOnly Property CardSurchargePaid() As String
            Get
                Return ResourceManager.GetString("CardSurchargePaid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Card type.
        '''</summary>
        Friend Shared ReadOnly Property CardType() As String
            Get
                Return ResourceManager.GetString("CardType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Payment card renew options.
        '''</summary>
        Friend Shared ReadOnly Property cccontainer() As String
            Get
                Return ResourceManager.GetString("cccontainer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your certificate will need to be valid on.
        '''</summary>
        Friend Shared ReadOnly Property CertificateValidFrom() As String
            Get
                Return ResourceManager.GetString("CertificateValidFrom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vehicle details.
        '''</summary>
        Friend Shared ReadOnly Property CheckDetailsHeader() As String
            Get
                Return ResourceManager.GetString("CheckDetailsHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vehicle registration number.
        '''</summary>
        Friend Shared ReadOnly Property CheckDetailsNumberPlateMessage() As String
            Get
                Return ResourceManager.GetString("CheckDetailsNumberPlateMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CO₂ emissions.
        '''</summary>
        Friend Shared ReadOnly Property Co2Text() As String
            Get
                Return ResourceManager.GetString("Co2Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Continue.
        '''</summary>
        Friend Shared ReadOnly Property ContinueText() As String
            Get
                Return ResourceManager.GetString("ContinueText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Up to the first 3 characters of surname of disability exemption certificate holder e.g. woz.
        '''</summary>
        Friend Shared ReadOnly Property CustomerSurname() As String
            Get
                Return ResourceManager.GetString("CustomerSurname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please provide the first 3 characters of your surname.
        '''</summary>
        Friend Shared ReadOnly Property CustomerSurnameErrorPrompt() As String
            Get
                Return ResourceManager.GetString("CustomerSurnameErrorPrompt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cylinder capacity (cc).
        '''</summary>
        Friend Shared ReadOnly Property CylinderCapacityText() As String
            Get
                Return ResourceManager.GetString("CylinderCapacityText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter the date of birth of the disability exemption certificate holder (DD/MM/YYYY).
        '''</summary>
        Friend Shared ReadOnly Property DateOfBirth() As String
            Get
                Return ResourceManager.GetString("DateOfBirth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter a correct date of birth.
        '''</summary>
        Friend Shared ReadOnly Property DateOfBirthErrorPrompt() As String
            Get
                Return ResourceManager.GetString("DateOfBirthErrorPrompt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date of first registration.
        '''</summary>
        Friend Shared ReadOnly Property DateOfFirstRegistrationText() As String
            Get
                Return ResourceManager.GetString("DateOfFirstRegistrationText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date of last V5C issued.
        '''</summary>
        Friend Shared ReadOnly Property DateofLastV5CIssuedText() As String
            Get
                Return ResourceManager.GetString("DateofLastV5CIssuedText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date of liability.
        '''</summary>
        Friend Shared ReadOnly Property DateOfLiability() As String
            Get
                Return ResourceManager.GetString("DateOfLiability", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} days ago.
        '''</summary>
        Friend Shared ReadOnly Property DaysAgo() As String
            Get
                Return ResourceManager.GetString("DaysAgo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Direct debit renew options.
        '''</summary>
        Friend Shared ReadOnly Property ddcontainer() As String
            Get
                Return ResourceManager.GetString("ddcontainer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Displaying.
        '''</summary>
        Friend Shared ReadOnly Property Displaying() As String
            Get
                Return ResourceManager.GetString("Displaying", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Duration.
        '''</summary>
        Friend Shared ReadOnly Property Duration() As String
            Get
                Return ResourceManager.GetString("Duration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must select a make from the list or enter your vehicle make in the text field.
        '''</summary>
        Friend Shared ReadOnly Property EitherMakeFromDDLorTextBox() As String
            Get
                Return ResourceManager.GetString("EitherMakeFromDDLorTextBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The email address and/or mobile number supplied by you may also be used to ask about your experience of using this service, or to gain further insight around other motoring services.&lt;br/&gt;The DVLA does not share mobile phone numbers or email addresses with any outside organisations..
        '''</summary>
        Friend Shared ReadOnly Property EmailAddressDeclaration() As String
            Get
                Return ResourceManager.GetString("EmailAddressDeclaration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please tick if you wish to be sent information..
        '''</summary>
        Friend Shared ReadOnly Property EmailAddressOptOut() As String
            Get
                Return ResourceManager.GetString("EmailAddressOptOut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An email will be sent to confirm your transaction if you provide a valid email address. DVLA will not send you an acknowledgement letter..
        '''</summary>
        Friend Shared ReadOnly Property EmailAddressSornDeclarationText() As String
            Get
                Return ResourceManager.GetString("EmailAddressSornDeclarationText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email address (optional. An email will be sent to confirm your transaction)..
        '''</summary>
        Friend Shared ReadOnly Property EmailAddressText() As String
            Get
                Return ResourceManager.GetString("EmailAddressText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter a valid email address.
        '''</summary>
        Friend Shared ReadOnly Property EmailConfirmationText() As String
            Get
                Return ResourceManager.GetString("EmailConfirmationText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VED exemption certificate serial number (found on your WPMS or DLA404 certificate issued by SPVA &amp; DWP).
        '''</summary>
        Friend Shared ReadOnly Property ExemptionCertificateNumber() As String
            Get
                Return ResourceManager.GetString("ExemptionCertificateNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter your serial number.
        '''</summary>
        Friend Shared ReadOnly Property ExemptionCertificateNumberErrorPrompt() As String
            Get
                Return ResourceManager.GetString("ExemptionCertificateNumberErrorPrompt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export marker.
        '''</summary>
        Friend Shared ReadOnly Property ExportMarkerText() As String
            Get
                Return ResourceManager.GetString("ExportMarkerText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Finished.
        '''</summary>
        Friend Shared ReadOnly Property Finish() As String
            Get
                Return ResourceManager.GetString("Finish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to for.
        '''</summary>
        Friend Shared ReadOnly Property ForText() As String
            Get
                Return ResourceManager.GetString("ForText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to for vehicle registration.
        '''</summary>
        Friend Shared ReadOnly Property ForVehicleRegistrationText() As String
            Get
                Return ResourceManager.GetString("ForVehicleRegistrationText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fuel type.
        '''</summary>
        Friend Shared ReadOnly Property FuelTypeText() As String
            Get
                Return ResourceManager.GetString("FuelTypeText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property GlobalMessage() As String
            Get
                Return ResourceManager.GetString("GlobalMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please include the incorrect V5C registration certificate for amendment..
        '''</summary>
        Friend Shared ReadOnly Property IncludeV5CMessage() As String
            Get
                Return ResourceManager.GetString("IncludeV5CMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If you think that the details on the vehicle record are incorrect please write to:.
        '''</summary>
        Friend Shared ReadOnly Property IncorrectVehicleDetailsMessage() As String
            Get
                Return ResourceManager.GetString("IncorrectVehicleDetailsMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item.
        '''</summary>
        Friend Shared ReadOnly Property Item() As String
            Get
                Return ResourceManager.GetString("Item", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mobile number (optional).
        '''</summary>
        Friend Shared ReadOnly Property MobileNumberText() As String
            Get
                Return ResourceManager.GetString("MobileNumberText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter a valid mobile number.
        '''</summary>
        Friend Shared ReadOnly Property MobileNumberValidatorText() As String
            Get
                Return ResourceManager.GetString("MobileNumberValidatorText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1 month ago.
        '''</summary>
        Friend Shared ReadOnly Property MonthAgo() As String
            Get
                Return ResourceManager.GetString("MonthAgo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to month vehicle tax.
        '''</summary>
        Friend Shared ReadOnly Property MonthConfirmationText() As String
            Get
                Return ResourceManager.GetString("MonthConfirmationText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} months ago.
        '''</summary>
        Friend Shared ReadOnly Property MonthsAgo() As String
            Get
                Return ResourceManager.GetString("MonthsAgo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select the appropriate declaration:.
        '''</summary>
        Friend Shared ReadOnly Property MotDeclaration() As String
            Get
                Return ResourceManager.GetString("MotDeclaration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I declare this is correct.
        '''</summary>
        Friend Shared ReadOnly Property MotDeclarationCorrect() As String
            Get
                Return ResourceManager.GetString("MotDeclarationCorrect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select a MOT/GVT declaration.
        '''</summary>
        Friend Shared ReadOnly Property MotDeclarationErrorMessage() As String
            Get
                Return ResourceManager.GetString("MotDeclarationErrorMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I declare this is incorrect.
        '''</summary>
        Friend Shared ReadOnly Property MotDeclarationIncorrect() As String
            Get
                Return ResourceManager.GetString("MotDeclarationIncorrect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to National Insurance (NI) number of disability exemption certificate holder e.g. AB123456X.
        '''</summary>
        Friend Shared ReadOnly Property NiNumber() As String
            Get
                Return ResourceManager.GetString("NiNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter a valid National Insurance number.
        '''</summary>
        Friend Shared ReadOnly Property NiNumberErrorPrompt() As String
            Get
                Return ResourceManager.GetString("NiNumberErrorPrompt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I don&apos;t have the V11 reminder, just the registration certificate.
        '''</summary>
        Friend Shared ReadOnly Property NoReminderSornMessage() As String
            Get
                Return ResourceManager.GetString("NoReminderSornMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I don&apos;t have the V11 reminder, just the registration certificate.
        '''</summary>
        Friend Shared ReadOnly Property NoReminderTaxMessage() As String
            Get
                Return ResourceManager.GetString("NoReminderTaxMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You can SORN your vehicle online using the vehicle registration number (number plate) and registration certificate (log book)..
        '''</summary>
        Friend Shared ReadOnly Property NoV11HeaderSORN() As String
            Get
                Return ResourceManager.GetString("NoV11HeaderSORN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of axles.
        '''</summary>
        Friend Shared ReadOnly Property NumberOfAxles() As String
            Get
                Return ResourceManager.GetString("NumberOfAxles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number plate.
        '''</summary>
        Friend Shared ReadOnly Property NumberPlate() As String
            Get
                Return ResourceManager.GetString("NumberPlate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to of.
        '''</summary>
        Friend Shared ReadOnly Property OfText() As String
            Get
                Return ResourceManager.GetString("OfText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Monthly by direct debit totalling.
        '''</summary>
        Friend Shared ReadOnly Property OneMonthly() As String
            Get
                Return ResourceManager.GetString("OneMonthly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Payment summary.
        '''</summary>
        Friend Shared ReadOnly Property PaymentSummary() As String
            Get
                Return ResourceManager.GetString("PaymentSummary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pay now.
        '''</summary>
        Friend Shared ReadOnly Property PayNowButtonText() As String
            Get
                Return ResourceManager.GetString("PayNowButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Price.
        '''</summary>
        Friend Shared ReadOnly Property Price() As String
            Get
                Return ResourceManager.GetString("Price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to How long do you want to renew for?.
        '''</summary>
        Friend Shared ReadOnly Property RenewalPeriodHeaderText() As String
            Get
                Return ResourceManager.GetString("RenewalPeriodHeaderText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Done.
        '''</summary>
        Friend Shared ReadOnly Property RenewTaxConfirmationText() As String
            Get
                Return ResourceManager.GetString("RenewTaxConfirmationText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vehicle details.
        '''</summary>
        Friend Shared ReadOnly Property RenewTaxConfirmVehicleText() As String
            Get
                Return ResourceManager.GetString("RenewTaxConfirmVehicleText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Renew vehicle tax.
        '''</summary>
        Friend Shared ReadOnly Property RenewTaxHeader() As String
            Get
                Return ResourceManager.GetString("RenewTaxHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pay.
        '''</summary>
        Friend Shared ReadOnly Property RenewTaxPaymentText() As String
            Get
                Return ResourceManager.GetString("RenewTaxPaymentText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your vehicle.
        '''</summary>
        Friend Shared ReadOnly Property RenewTaxReferenceNumberStepText() As String
            Get
                Return ResourceManager.GetString("RenewTaxReferenceNumberStepText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Renewal period check.
        '''</summary>
        Friend Shared ReadOnly Property RenewTaxVEDConfirmationText() As String
            Get
                Return ResourceManager.GetString("RenewTaxVEDConfirmationText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Renewal period.
        '''</summary>
        Friend Shared ReadOnly Property RenewTaxVedPickerText() As String
            Get
                Return ResourceManager.GetString("RenewTaxVedPickerText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search again.
        '''</summary>
        Friend Shared ReadOnly Property SearchAgainButtonText() As String
            Get
                Return ResourceManager.GetString("SearchAgainButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search.
        '''</summary>
        Friend Shared ReadOnly Property SearchButtonText() As String
            Get
                Return ResourceManager.GetString("SearchButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select.
        '''</summary>
        Friend Shared ReadOnly Property SelectText() As String
            Get
                Return ResourceManager.GetString("SelectText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Service.
        '''</summary>
        Friend Shared ReadOnly Property Service() As String
            Get
                Return ResourceManager.GetString("Service", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 6 monthly by direct debit totalling.
        '''</summary>
        Friend Shared ReadOnly Property SixMonthly() As String
            Get
                Return ResourceManager.GetString("SixMonthly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 6 Months rate.
        '''</summary>
        Friend Shared ReadOnly Property SixMonthRate() As String
            Get
                Return ResourceManager.GetString("SixMonthRate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 6 Months.
        '''</summary>
        Friend Shared ReadOnly Property SixMonths() As String
            Get
                Return ResourceManager.GetString("SixMonths", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Make SORN.
        '''</summary>
        Friend Shared ReadOnly Property SornButtonText() As String
            Get
                Return ResourceManager.GetString("SornButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please be aware that if the vehicle has recently been taxed or a SORN declared, these details may not yet be updated on the vehicle record..
        '''</summary>
        Friend Shared ReadOnly Property SornDisclaimerText() As String
            Get
                Return ResourceManager.GetString("SornDisclaimerText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SORN a vehicle.
        '''</summary>
        Friend Shared ReadOnly Property SORNVehicle() As String
            Get
                Return ResourceManager.GetString("SORNVehicle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start date.
        '''</summary>
        Friend Shared ReadOnly Property StartDate() As String
            Get
                Return ResourceManager.GetString("StartDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select start date for your tax:.
        '''</summary>
        Friend Shared ReadOnly Property StartDatePrompt() As String
            Get
                Return ResourceManager.GetString("StartDatePrompt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select start date for your tax:.
        '''</summary>
        Friend Shared ReadOnly Property StartDatePrompt1() As String
            Get
                Return ResourceManager.GetString("StartDatePrompt1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If you choose to tax from the 1&lt;sup&gt;st&lt;/sup&gt; of the following month, please be aware that the vehicle will remain untaxed or a SORN will remain in force until the 1&lt;sup&gt;st&lt;/sup&gt; day of the next month.  The vehicle cannot be used or kept on a public road until the 1&lt;sup&gt;st&lt;/sup&gt; of the next month..
        '''</summary>
        Friend Shared ReadOnly Property StartDatePromptDeclaration() As String
            Get
                Return ResourceManager.GetString("StartDatePromptDeclaration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Submit declaration.
        '''</summary>
        Friend Shared ReadOnly Property SubmitDeclarationText() As String
            Get
                Return ResourceManager.GetString("SubmitDeclarationText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tax band.
        '''</summary>
        Friend Shared ReadOnly Property TaxBand() As String
            Get
                Return ResourceManager.GetString("TaxBand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tax class.
        '''</summary>
        Friend Shared ReadOnly Property TaxClass() As String
            Get
                Return ResourceManager.GetString("TaxClass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The tax disc will be dispatched to the registered keeper of the vehicle address currently held by DVLA and should arrive within 5 working days..
        '''</summary>
        Friend Shared ReadOnly Property TaxDiscDeliveryMessage() As String
            Get
                Return ResourceManager.GetString("TaxDiscDeliveryMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thank you for your payment.
        '''</summary>
        Friend Shared ReadOnly Property ThankYouPaymentText() As String
            Get
                Return ResourceManager.GetString("ThankYouPaymentText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Today.
        '''</summary>
        Friend Shared ReadOnly Property Today() As String
            Get
                Return ResourceManager.GetString("Today", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property Total() As String
            Get
                Return ResourceManager.GetString("Total", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to to.
        '''</summary>
        Friend Shared ReadOnly Property ToText() As String
            Get
                Return ResourceManager.GetString("ToText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Try again.
        '''</summary>
        Friend Shared ReadOnly Property TryAgain() As String
            Get
                Return ResourceManager.GetString("TryAgain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 12 monthly by direct debit totalling.
        '''</summary>
        Friend Shared ReadOnly Property TwelveMonthly() As String
            Get
                Return ResourceManager.GetString("TwelveMonthly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 12 Months rate.
        '''</summary>
        Friend Shared ReadOnly Property TwelvemonthRate() As String
            Get
                Return ResourceManager.GetString("TwelvemonthRate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 12 Months.
        '''</summary>
        Friend Shared ReadOnly Property TwelveMonths() As String
            Get
                Return ResourceManager.GetString("TwelveMonths", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select one of the following options.
        '''</summary>
        Friend Shared ReadOnly Property UserTypeErrorMessageMin() As String
            Get
                Return ResourceManager.GetString("UserTypeErrorMessageMin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter the full 16 digit number.
        '''</summary>
        Friend Shared ReadOnly Property V11ErrorMessage() As String
            Get
                Return ResourceManager.GetString("V11ErrorMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must enter your 16 digit reference number.
        '''</summary>
        Friend Shared ReadOnly Property V11ErrorMessageMin() As String
            Get
                Return ResourceManager.GetString("V11ErrorMessageMin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your V11 reminder reference number can be found on the front of your V11 reminder :.
        '''</summary>
        Friend Shared ReadOnly Property V11RefNumImageText() As String
            Get
                Return ResourceManager.GetString("V11RefNumImageText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First we need your vehicle details.
        '''</summary>
        Friend Shared ReadOnly Property V11ReminderHeader() As String
            Get
                Return ResourceManager.GetString("V11ReminderHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please type the 16 digit reference number from your V11 reminder.
        '''</summary>
        Friend Shared ReadOnly Property V11ReminderMessage() As String
            Get
                Return ResourceManager.GetString("V11ReminderMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://www.gov.uk/government/publications/rates-of-vehicle-tax-v149.
        '''</summary>
        Friend Shared ReadOnly Property V149Link() As String
            Get
                Return ResourceManager.GetString("V149Link", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rates of vehicle tax (V149).
        '''</summary>
        Friend Shared ReadOnly Property V149Text() As String
            Get
                Return ResourceManager.GetString("V149Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GB new keeper - please enter the full 12 digit number from your V5C/2. NI new keeper – sorry, due to NI insurance legislation, new keepers must tax at a Post Office® branch that deals with vehicle tax..
        '''</summary>
        Friend Shared ReadOnly Property V5C2ErrorMessage() As String
            Get
                Return ResourceManager.GetString("V5C2ErrorMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must enter your 12 digit reference number.
        '''</summary>
        Friend Shared ReadOnly Property V5C2ErrorMessageMin() As String
            Get
                Return ResourceManager.GetString("V5C2ErrorMessageMin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your V5C/2 document reference number can be found on the front of your V5C/2 :.
        '''</summary>
        Friend Shared ReadOnly Property V5C2ImageText() As String
            Get
                Return ResourceManager.GetString("V5C2ImageText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please type the 12 digit reference number from the front of your new keeper supplement (V5C/2).
        '''</summary>
        Friend Shared ReadOnly Property V5C2NumberMessage() As String
            Get
                Return ResourceManager.GetString("V5C2NumberMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to V5C document reference number (optional).
        '''</summary>
        Friend Shared ReadOnly Property V5CDocumentReferenceNumberText() As String
            Get
                Return ResourceManager.GetString("V5CDocumentReferenceNumberText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter the full 11 digit number.
        '''</summary>
        Friend Shared ReadOnly Property V5CErrorMessage() As String
            Get
                Return ResourceManager.GetString("V5CErrorMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must enter your 11 digit reference number.
        '''</summary>
        Friend Shared ReadOnly Property V5CErrorMessageMin() As String
            Get
                Return ResourceManager.GetString("V5CErrorMessageMin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your V5C document reference number can be found on the front of your V5C :.
        '''</summary>
        Friend Shared ReadOnly Property V5CImageText() As String
            Get
                Return ResourceManager.GetString("V5CImageText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please type the 11 digit reference number from the front of your registration certificate.
        '''</summary>
        Friend Shared ReadOnly Property V5CNumberMessage() As String
            Get
                Return ResourceManager.GetString("V5CNumberMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Existing keeper (using V5C document reference number).
        '''</summary>
        Friend Shared ReadOnly Property V5CRadioText1() As String
            Get
                Return ResourceManager.GetString("V5CRadioText1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New keeper (using V5C/2 new keeper supplement document reference number).
        '''</summary>
        Friend Shared ReadOnly Property V5CRadioText2() As String
            Get
                Return ResourceManager.GetString("V5CRadioText2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add your registration number.
        '''</summary>
        Friend Shared ReadOnly Property V5CVRMMessage() As String
            Get
                Return ResourceManager.GetString("V5CVRMMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to valid from.
        '''</summary>
        Friend Shared ReadOnly Property ValidFrom() As String
            Get
                Return ResourceManager.GetString("ValidFrom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;p&gt;VCS&lt;/p&gt;
        '''&lt;p&gt;DVLA&lt;/p&gt;
        '''&lt;p&gt;Swansea&lt;/p&gt;
        '''&lt;p&gt;SA99 1BA&lt;/p&gt;.
        '''</summary>
        Friend Shared ReadOnly Property VCSAddress() As String
            Get
                Return ResourceManager.GetString("VCSAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VED commencement date.
        '''</summary>
        Friend Shared ReadOnly Property VedCommencementDate() As String
            Get
                Return ResourceManager.GetString("VedCommencementDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The vehicle tax you applied for is:.
        '''</summary>
        Friend Shared ReadOnly Property VEDConfirmationHeader() As String
            Get
                Return ResourceManager.GetString("VEDConfirmationHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you happy to continue? The details are:.
        '''</summary>
        Friend Shared ReadOnly Property VEDContinueMessage() As String
            Get
                Return ResourceManager.GetString("VEDContinueMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VED exempt.
        '''</summary>
        Friend Shared ReadOnly Property VedExempt() As String
            Get
                Return ResourceManager.GetString("VedExempt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VED exemption certificate serial number.
        '''</summary>
        Friend Shared ReadOnly Property VedExemptionCertificateNumber() As String
            Get
                Return ResourceManager.GetString("VedExemptionCertificateNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select the vehicle tax you would like for the vehicle.
        '''</summary>
        Friend Shared ReadOnly Property VEDValidationMessage() As String
            Get
                Return ResourceManager.GetString("VEDValidationMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vehicle colour.
        '''</summary>
        Friend Shared ReadOnly Property VehicleColourText() As String
            Get
                Return ResourceManager.GetString("VehicleColourText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vehicle enquiry.
        '''</summary>
        Friend Shared ReadOnly Property VehicleEnquiryHeader() As String
            Get
                Return ResourceManager.GetString("VehicleEnquiryHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To make an enquiry enter the vehicle registration number (number plate) and the vehicle make..
        '''</summary>
        Friend Shared ReadOnly Property VehicleEnquiryText() As String
            Get
                Return ResourceManager.GetString("VehicleEnquiryText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vehicle excise duty.
        '''</summary>
        Friend Shared ReadOnly Property VehicleExciseDutyRateForVehicleText() As String
            Get
                Return ResourceManager.GetString("VehicleExciseDutyRateForVehicleText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vehicle make.
        '''</summary>
        Friend Shared ReadOnly Property VehicleMake() As String
            Get
                Return ResourceManager.GetString("VehicleMake", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The V5C reference number you have provided should be 11 digits.
        '''</summary>
        Friend Shared ReadOnly Property VehicleREV5CMaxValidation() As String
            Get
                Return ResourceManager.GetString("VehicleREV5CMaxValidation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your reference number should contain 11 digits only.
        '''</summary>
        Friend Shared ReadOnly Property VehicleREV5CMinValidation() As String
            Get
                Return ResourceManager.GetString("VehicleREV5CMinValidation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select your vehicle from the drop down or enter your make in the &apos;other&apos; field.
        '''</summary>
        Friend Shared ReadOnly Property VehicleSearchDDLMaxValidation() As String
            Get
                Return ResourceManager.GetString("VehicleSearchDDLMaxValidation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must select your vehicle make from the list.
        '''</summary>
        Friend Shared ReadOnly Property VehicleSearchDDLMinValidation() As String
            Get
                Return ResourceManager.GetString("VehicleSearchDDLMinValidation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must enter your registration number in a valid format.
        '''</summary>
        Friend Shared ReadOnly Property VehicleSearchMaxValidation() As String
            Get
                Return ResourceManager.GetString("VehicleSearchMaxValidation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The registration number you provided is invalid.
        '''</summary>
        Friend Shared ReadOnly Property VehicleSearchMinValidation() As String
            Get
                Return ResourceManager.GetString("VehicleSearchMinValidation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must enter your registration number in order to view your vehicle record.
        '''</summary>
        Friend Shared ReadOnly Property VehicleSearchRequiredMaxValidationText() As String
            Get
                Return ResourceManager.GetString("VehicleSearchRequiredMaxValidationText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter your registration number.
        '''</summary>
        Friend Shared ReadOnly Property VehicleSearchRequiredMinValidationText() As String
            Get
                Return ResourceManager.GetString("VehicleSearchRequiredMinValidationText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tax/SORN status.
        '''</summary>
        Friend Shared ReadOnly Property VehicleSornStatus() As String
            Get
                Return ResourceManager.GetString("VehicleSornStatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vehicle status.
        '''</summary>
        Friend Shared ReadOnly Property VehicleStatusText() As String
            Get
                Return ResourceManager.GetString("VehicleStatusText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vehicle type approval.
        '''</summary>
        Friend Shared ReadOnly Property VehicleTypeApprovalText() As String
            Get
                Return ResourceManager.GetString("VehicleTypeApprovalText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Registration number.
        '''</summary>
        Friend Shared ReadOnly Property VehicleVRN() As String
            Get
                Return ResourceManager.GetString("VehicleVRN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must enter your registration number.
        '''</summary>
        Friend Shared ReadOnly Property VRMErrorMessage() As String
            Get
                Return ResourceManager.GetString("VRMErrorMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must enter your registration number.
        '''</summary>
        Friend Shared ReadOnly Property VRMErrorMessageMin() As String
            Get
                Return ResourceManager.GetString("VRMErrorMessageMin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Where to find this.
        '''</summary>
        Friend Shared ReadOnly Property WhereToFindThisText() As String
            Get
                Return ResourceManager.GetString("WhereToFindThisText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Where is my V11 reminder reference number?.
        '''</summary>
        Friend Shared ReadOnly Property WhereV11Num() As String
            Get
                Return ResourceManager.GetString("WhereV11Num", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Where is my V5C/2 document reference number?.
        '''</summary>
        Friend Shared ReadOnly Property WhereV5C2Num() As String
            Get
                Return ResourceManager.GetString("WhereV5C2Num", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Where is my V5C document reference number?.
        '''</summary>
        Friend Shared ReadOnly Property WhereV5CNum() As String
            Get
                Return ResourceManager.GetString("WhereV5CNum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1 year ago.
        '''</summary>
        Friend Shared ReadOnly Property YearAgo() As String
            Get
                Return ResourceManager.GetString("YearAgo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Year of manufacture.
        '''</summary>
        Friend Shared ReadOnly Property YearOfManufactureText() As String
            Get
                Return ResourceManager.GetString("YearOfManufactureText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} years ago.
        '''</summary>
        Friend Shared ReadOnly Property YearsAgo() As String
            Get
                Return ResourceManager.GetString("YearsAgo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Yesterday.
        '''</summary>
        Friend Shared ReadOnly Property Yesterday() As String
            Get
                Return ResourceManager.GetString("Yesterday", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
